# Generated by Django 3.0.5 on 2020-12-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=70)),
                ('last_name', models.CharField(default='', max_length=70)),
                ('password', models.CharField(default='', max_length=200)),
                ('email_id', models.CharField(default='', max_length=70)),
                ('contact', models.CharField(default='', max_length=15)),
                ('otp', models.CharField(default='', max_length=6)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
